(* GENERATED by tools/render_coverings.py from plugin/keel/clauses.json -- do not edit.
   One block per side of every shipped clause, instantiating proofs/Coverings.v on it.
   tools/check_coq.py compiles this and grades every result for axioms.
   PARAMETERS: Text scan mention *)
Require Import List String.
Import ListNotations.
Require Import Coverings.
Open Scope string_scope.

Section Instance.
  Variable Text : Type.
  Variable scan : Text -> list (Segment string).
  Variable mention : Text -> Text.

  (* SIDE A01_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE A01_discharged_by *)
  (* class=effect closure=world *)
  (* effects: observed_read -- what the act did, read from the world, not the command *)
  Theorem A01_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem A01_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE A02_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE A02_discharged_by *)
  (* class=composed closure=host *)
  (* class=effect closure=world *)
  (* effects: observed_read -- what the act did, read from the world, not the command *)
  Theorem A02_discharged_by_branch0_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem A02_discharged_by_branch0_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=effect closure=world *)
  (* effects: report_paths -- what the act did, read from the world, not the command *)
  Theorem A02_discharged_by_branch2_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem A02_discharged_by_branch2_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE A03_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE A03_discharged_by *)
  (* class=effect closure=world *)
  (* effects: remote_read -- what the act did, read from the world, not the command *)
  Theorem A03_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem A03_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE C03-verify-what-returns_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE C03-verify-what-returns_activated_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE C03-verify-what-returns_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE C08-check-can-fail_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE C08-check-can-fail_activated_by *)
  (* class=effect closure=world *)
  (* effects: report_pass -- what the act did, read from the world, not the command *)
  Theorem C08_check_can_fail_activated_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem C08_check_can_fail_activated_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE C08-check-can-fail_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_fail -- what the act did, read from the world, not the command *)
  Theorem C08_check_can_fail_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem C08_check_can_fail_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE C09-checker-excludes-self_fingerprint *)
  (* class=effect closure=world *)
  (* effects: report_self -- what the act did, read from the world, not the command *)
  Theorem C09_checker_excludes_self_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem C09_checker_excludes_self_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE C09-checker-excludes-self_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_listing -- what the act did, read from the world, not the command *)
  Theorem C09_checker_excludes_self_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem C09_checker_excludes_self_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE D01_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE D01_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P01_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P01_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P02_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P02_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE T01_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE T01_discharged_by *)
  (* class=effect closure=world *)
  (* effects: observed_read -- what the act did, read from the world, not the command *)
  Theorem T01_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem T01_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE T02_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE T02_activated_by *)
  (* class=effect closure=world *)
  (* effects: remote_ref_moved -- what the act did, read from the world, not the command *)
  Theorem T02_activated_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem T02_activated_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE T02_discharged_by *)
  (* class=effect closure=world *)
  (* effects: remote_landed -- what the act did, read from the world, not the command *)
  Theorem T02_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem T02_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U01_fingerprint *)
  (* class=effect closure=world *)
  (* effects: pids_spawned -- what the act did, read from the world, not the command *)
  Theorem U01_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U01_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U01_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_pass -- what the act did, read from the world, not the command *)
  Theorem U01_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U01_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U02_fingerprint *)
  (* class=effect closure=world *)
  (* effects: pids_spawned_again -- what the act did, read from the world, not the command *)
  Theorem U02_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U02_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U02_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_after_change -- what the act did, read from the world, not the command *)
  Theorem U02_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U02_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U03_fingerprint *)
  (* class=effect closure=world *)
  (* effects: pids_gone -- what the act did, read from the world, not the command *)
  Theorem U03_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U03_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U03_discharged_by *)
  (* class=effect closure=world *)
  (* effects: observed_read, report_pids -- what the act did, read from the world, not the command *)
  Theorem U03_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U03_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U06_fingerprint *)
  (* class=effect closure=world *)
  (* effects: net_out -- what the act did, read from the world, not the command *)
  Theorem U06_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U06_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U06_discharged_by *)
  (* class=effect closure=world *)
  (* effects: net_read -- what the act did, read from the world, not the command *)
  Theorem U06_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U06_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U08_fingerprint *)
  (* class=effect closure=world *)
  (* effects: commit_signed -- what the act did, read from the world, not the command *)
  Theorem U08_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U08_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U08_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_signature -- what the act did, read from the world, not the command *)
  Theorem U08_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U08_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U09_fingerprint *)
  (* class=effect closure=world *)
  (* effects: head_switched -- what the act did, read from the world, not the command *)
  Theorem U09_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U09_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U09_discharged_by *)
  (* class=effect closure=world *)
  (* effects: observed_read, report_ref -- what the act did, read from the world, not the command *)
  Theorem U09_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U09_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U10_fingerprint *)
  (* class=effect closure=world *)
  (* effects: report_null -- what the act did, read from the world, not the command *)
  Theorem U10_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U10_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U10_discharged_by *)
  (* class=composed closure=host *)
  (* class=effect closure=world *)
  (* effects: report_structured -- what the act did, read from the world, not the command *)
  Theorem U10_discharged_by_branch0_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U10_discharged_by_branch0_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE U12_fingerprint *)
  (* class=effect closure=world *)
  (* effects: files_changed -- what the act did, read from the world, not the command *)
  Theorem U12_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U12_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U12_discharged_by *)
  (* class=composed closure=host *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=effect closure=world *)
  (* effects: report_paths -- what the act did, read from the world, not the command *)
  Theorem U12_discharged_by_branch2_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U12_discharged_by_branch2_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U13_fingerprint *)
  (* class=effect closure=world *)
  (* effects: files_changed -- what the act did, read from the world, not the command *)
  Theorem U13_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U13_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U13_discharged_by *)
  (* class=composed closure=host *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=effect closure=world *)
  (* effects: report_paths -- what the act did, read from the world, not the command *)
  Theorem U13_discharged_by_branch1_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U13_discharged_by_branch1_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U19_fingerprint *)
  (* class=effect closure=world *)
  (* effects: files_changed -- what the act did, read from the world, not the command *)
  Theorem U19_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U19_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U19_discharged_by *)
  (* class=composed closure=host *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)
  (* class=effect closure=world *)
  (* effects: report_paths -- what the act did, read from the world, not the command *)
  Theorem U19_discharged_by_branch2_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U19_discharged_by_branch2_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U20_fingerprint *)
  (* class=effect closure=world *)
  (* effects: files_removed, head_reset -- what the act did, read from the world, not the command *)
  Theorem U20_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U20_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U20_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_fail, report_pass -- what the act did, read from the world, not the command *)
  Theorem U20_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U20_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U24_fingerprint *)
  (* class=effect closure=world *)
  (* effects: net_out -- what the act did, read from the world, not the command *)
  Theorem U24_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U24_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U24_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_nowarn -- what the act did, read from the world, not the command *)
  Theorem U24_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U24_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U25_fingerprint *)
  (* class=effect closure=world *)
  (* effects: report_clean -- what the act did, read from the world, not the command *)
  Theorem U25_fingerprint_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U25_fingerprint_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

  (* SIDE U25_discharged_by *)
  (* class=effect closure=world *)
  (* effects: report_fail -- what the act did, read from the world, not the command *)
  Theorem U25_discharged_by_name_agnostic : forall (Delta : Type) (E : Delta -> Prop) (d : Delta),
    name_agnostic string (effect string E d).
  Proof. intros Delta E d. exact (effect_is_name_agnostic string Delta E d). Qed.
  Theorem U25_discharged_by_separates : forall (Delta : Type) (E : Delta -> Prop) (d d' : Delta), E d -> ~ E d' ->
    forall segs, effect string E d segs /\ ~ effect string E d' segs.
  Proof. intros Delta E d d'. exact (effect_separates_same_segments string Delta E d d'). Qed.

End Instance.

Print Assumptions A01_discharged_by_name_agnostic.
Print Assumptions A01_discharged_by_separates.
Print Assumptions A02_discharged_by_branch0_name_agnostic.
Print Assumptions A02_discharged_by_branch0_separates.
Print Assumptions A02_discharged_by_branch2_name_agnostic.
Print Assumptions A02_discharged_by_branch2_separates.
Print Assumptions A03_discharged_by_name_agnostic.
Print Assumptions A03_discharged_by_separates.
Print Assumptions C08_check_can_fail_activated_by_name_agnostic.
Print Assumptions C08_check_can_fail_activated_by_separates.
Print Assumptions C08_check_can_fail_discharged_by_name_agnostic.
Print Assumptions C08_check_can_fail_discharged_by_separates.
Print Assumptions C09_checker_excludes_self_fingerprint_name_agnostic.
Print Assumptions C09_checker_excludes_self_fingerprint_separates.
Print Assumptions C09_checker_excludes_self_discharged_by_name_agnostic.
Print Assumptions C09_checker_excludes_self_discharged_by_separates.
Print Assumptions T01_discharged_by_name_agnostic.
Print Assumptions T01_discharged_by_separates.
Print Assumptions T02_activated_by_name_agnostic.
Print Assumptions T02_activated_by_separates.
Print Assumptions T02_discharged_by_name_agnostic.
Print Assumptions T02_discharged_by_separates.
Print Assumptions U01_fingerprint_name_agnostic.
Print Assumptions U01_fingerprint_separates.
Print Assumptions U01_discharged_by_name_agnostic.
Print Assumptions U01_discharged_by_separates.
Print Assumptions U02_fingerprint_name_agnostic.
Print Assumptions U02_fingerprint_separates.
Print Assumptions U02_discharged_by_name_agnostic.
Print Assumptions U02_discharged_by_separates.
Print Assumptions U03_fingerprint_name_agnostic.
Print Assumptions U03_fingerprint_separates.
Print Assumptions U03_discharged_by_name_agnostic.
Print Assumptions U03_discharged_by_separates.
Print Assumptions U06_fingerprint_name_agnostic.
Print Assumptions U06_fingerprint_separates.
Print Assumptions U06_discharged_by_name_agnostic.
Print Assumptions U06_discharged_by_separates.
Print Assumptions U08_fingerprint_name_agnostic.
Print Assumptions U08_fingerprint_separates.
Print Assumptions U08_discharged_by_name_agnostic.
Print Assumptions U08_discharged_by_separates.
Print Assumptions U09_fingerprint_name_agnostic.
Print Assumptions U09_fingerprint_separates.
Print Assumptions U09_discharged_by_name_agnostic.
Print Assumptions U09_discharged_by_separates.
Print Assumptions U10_fingerprint_name_agnostic.
Print Assumptions U10_fingerprint_separates.
Print Assumptions U10_discharged_by_branch0_name_agnostic.
Print Assumptions U10_discharged_by_branch0_separates.
Print Assumptions U12_fingerprint_name_agnostic.
Print Assumptions U12_fingerprint_separates.
Print Assumptions U12_discharged_by_branch2_name_agnostic.
Print Assumptions U12_discharged_by_branch2_separates.
Print Assumptions U13_fingerprint_name_agnostic.
Print Assumptions U13_fingerprint_separates.
Print Assumptions U13_discharged_by_branch1_name_agnostic.
Print Assumptions U13_discharged_by_branch1_separates.
Print Assumptions U19_fingerprint_name_agnostic.
Print Assumptions U19_fingerprint_separates.
Print Assumptions U19_discharged_by_branch2_name_agnostic.
Print Assumptions U19_discharged_by_branch2_separates.
Print Assumptions U20_fingerprint_name_agnostic.
Print Assumptions U20_fingerprint_separates.
Print Assumptions U20_discharged_by_name_agnostic.
Print Assumptions U20_discharged_by_separates.
Print Assumptions U24_fingerprint_name_agnostic.
Print Assumptions U24_fingerprint_separates.
Print Assumptions U24_discharged_by_name_agnostic.
Print Assumptions U24_discharged_by_separates.
Print Assumptions U25_fingerprint_name_agnostic.
Print Assumptions U25_fingerprint_separates.
Print Assumptions U25_discharged_by_name_agnostic.
Print Assumptions U25_discharged_by_separates.
