(* GENERATED by tools/render_coverings.py from plugin/keel/clauses.json -- do not edit.
   One block per side of every shipped clause, instantiating proofs/Coverings.v on it.
   tools/check_coq.py compiles this and grades every result for axioms. *)
Require Import List String.
Import ListNotations.
Require Import Coverings.
Open Scope string_scope.

Section Instance.
  Variable Text : Type.
  Variable scan : Text -> list (Segment string).
  Variable mention : Text -> Text.
  Hypothesis scan_mention_single :
    forall c, scan (mention c) = [ {| seg_argv := ["echo"] |} ].

  (* SIDE A01_fingerprint *)
  (* class=nominal closure=open *)
  Definition A01_fingerprint_names : list string := ["git"].
  Lemma A01_fingerprint_clean : ~ In "echo" A01_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A01_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A01_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A01_fingerprint_clean). Qed.
  Theorem A01_fingerprint_monotone : forall W, (forall p, In p A01_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A01_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE A01_discharged_by *)
  (* class=nominal closure=open *)
  Definition A01_discharged_by_names : list string := ["git"].
  Lemma A01_discharged_by_clean : ~ In "echo" A01_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A01_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A01_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A01_discharged_by_clean). Qed.
  Theorem A01_discharged_by_monotone : forall W, (forall p, In p A01_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A01_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE A02_fingerprint *)
  (* class=nominal closure=open *)
  Definition A02_fingerprint_names : list string := ["rm"; "find"; "truncate"; "git"].
  Lemma A02_fingerprint_clean : ~ In "echo" A02_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A02_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A02_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A02_fingerprint_clean). Qed.
  Theorem A02_fingerprint_monotone : forall W, (forall p, In p A02_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A02_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE A02_discharged_by *)
  (* class=nominal closure=open *)
  Definition A02_discharged_by_names : list string := ["ls"; "find"; "du"; "git"].
  Lemma A02_discharged_by_clean : ~ In "echo" A02_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A02_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A02_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A02_discharged_by_clean). Qed.
  Theorem A02_discharged_by_monotone : forall W, (forall p, In p A02_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A02_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE A03_fingerprint *)
  (* class=nominal closure=open *)
  Definition A03_fingerprint_names : list string := ["git"].
  Lemma A03_fingerprint_clean : ~ In "echo" A03_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A03_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A03_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A03_fingerprint_clean). Qed.
  Theorem A03_fingerprint_monotone : forall W, (forall p, In p A03_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A03_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE A03_discharged_by *)
  (* class=nominal closure=open *)
  Definition A03_discharged_by_names : list string := ["git"].
  Lemma A03_discharged_by_clean : ~ In "echo" A03_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem A03_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p A03_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ A03_discharged_by_clean). Qed.
  Theorem A03_discharged_by_monotone : forall W, (forall p, In p A03_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p A03_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE C03-verify-what-returns_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE C03-verify-what-returns_activated_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE C03-verify-what-returns_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE C08-check-can-fail_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE C08-check-can-fail_activated_by *)
  (* class=nominal closure=open *)
  (* pattern 0: '(?:pytest|unittest|[^\\s]*(?:check|verify)[^\\s]*\\.(?:py|sh))' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem C08_check_can_fail_activated_by_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE C08-check-can-fail_discharged_by *)
  (* class=nominal closure=open *)
  (* pattern 0: '(?:pytest|unittest|[^\\s]*(?:check|verify)[^\\s]*\\.(?:py|sh))' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem C08_check_can_fail_discharged_by_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE C09-checker-excludes-self_fingerprint *)
  (* class=topology closure=topology *)
  Theorem C09_checker_excludes_self_fingerprint_name_agnostic : forall n, name_agnostic string (fun segs => List.length segs = n).
  Proof. exact (topology_is_name_agnostic string). Qed.

  (* SIDE C09-checker-excludes-self_discharged_by *)
  (* class=topology closure=topology *)
  Theorem C09_checker_excludes_self_discharged_by_name_agnostic : forall n, name_agnostic string (fun segs => List.length segs = n).
  Proof. exact (topology_is_name_agnostic string). Qed.

  (* SIDE D01_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE D01_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P01_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P01_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P02_fingerprint *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE P02_discharged_by *)
  (* class=tool-enum closure=host *)
  (* reads tool_name, a closed host enum: no text, no vocabulary *)

  (* SIDE T01_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE T01_discharged_by *)
  (* class=nominal closure=open *)
  Definition T01_discharged_by_names : list string := ["git"].
  Lemma T01_discharged_by_clean : ~ In "echo" T01_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem T01_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p T01_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ T01_discharged_by_clean). Qed.
  Theorem T01_discharged_by_monotone : forall W, (forall p, In p T01_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p T01_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE T02_fingerprint *)
  (* class=always closure=always *)
  (* terminal: fires on every event of its surface; the Theorem 3 boundary *)

  (* SIDE T02_activated_by *)
  (* class=nominal closure=open *)
  Definition T02_activated_by_names : list string := ["git"].
  Lemma T02_activated_by_clean : ~ In "echo" T02_activated_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem T02_activated_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p T02_activated_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ T02_activated_by_clean). Qed.
  Theorem T02_activated_by_monotone : forall W, (forall p, In p T02_activated_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p T02_activated_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE T02_discharged_by *)
  (* class=nominal closure=open *)
  Definition T02_discharged_by_names : list string := ["git"; "git"].
  Lemma T02_discharged_by_clean : ~ In "echo" T02_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem T02_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p T02_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ T02_discharged_by_clean). Qed.
  Theorem T02_discharged_by_monotone : forall W, (forall p, In p T02_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p T02_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U01_fingerprint *)
  (* class=nominal closure=shipped *)
  Definition U01_fingerprint_names : list string := ["dispatch.sh"].
  Lemma U01_fingerprint_clean : ~ In "echo" U01_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U01_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U01_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U01_fingerprint_clean). Qed.
  Theorem U01_fingerprint_monotone : forall W, (forall p, In p U01_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U01_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U01_discharged_by *)
  (* class=nominal closure=shipped *)
  Definition U01_discharged_by_names : list string := ["probe_child_capability.py"].
  Lemma U01_discharged_by_clean : ~ In "echo" U01_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U01_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U01_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U01_discharged_by_clean). Qed.
  Theorem U01_discharged_by_monotone : forall W, (forall p, In p U01_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U01_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U02_fingerprint *)
  (* class=nominal closure=shipped *)
  Definition U02_fingerprint_names : list string := ["dispatch.sh"].
  Lemma U02_fingerprint_clean : ~ In "echo" U02_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U02_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U02_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U02_fingerprint_clean). Qed.
  Theorem U02_fingerprint_monotone : forall W, (forall p, In p U02_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U02_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U02_discharged_by *)
  (* class=nominal closure=shipped *)
  Definition U02_discharged_by_names : list string := ["probe_child_capability.py"].
  Lemma U02_discharged_by_clean : ~ In "echo" U02_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U02_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U02_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U02_discharged_by_clean). Qed.
  Theorem U02_discharged_by_monotone : forall W, (forall p, In p U02_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U02_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U03_fingerprint *)
  (* class=nominal closure=open *)
  Definition U03_fingerprint_names : list string := ["kill"; "killall"; "pkill"].
  Lemma U03_fingerprint_clean : ~ In "echo" U03_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U03_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U03_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U03_fingerprint_clean). Qed.
  Theorem U03_fingerprint_monotone : forall W, (forall p, In p U03_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U03_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U03_discharged_by *)
  (* class=nominal closure=open *)
  Definition U03_discharged_by_names : list string := ["ps"; "pgrep"].
  Lemma U03_discharged_by_clean : ~ In "echo" U03_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U03_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U03_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U03_discharged_by_clean). Qed.
  Theorem U03_discharged_by_monotone : forall W, (forall p, In p U03_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U03_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U06_fingerprint *)
  (* class=nominal closure=open *)
  Definition U06_fingerprint_names : list string := ["curl"].
  Lemma U06_fingerprint_clean : ~ In "echo" U06_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U06_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U06_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U06_fingerprint_clean). Qed.
  Theorem U06_fingerprint_monotone : forall W, (forall p, In p U06_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U06_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U06_discharged_by *)
  (* class=nominal closure=open *)
  Definition U06_discharged_by_names : list string := ["curl"].
  Lemma U06_discharged_by_clean : ~ In "echo" U06_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U06_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U06_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U06_discharged_by_clean). Qed.
  Theorem U06_discharged_by_monotone : forall W, (forall p, In p U06_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U06_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U08_fingerprint *)
  (* class=nominal closure=open *)
  Definition U08_fingerprint_names : list string := ["git"].
  Lemma U08_fingerprint_clean : ~ In "echo" U08_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U08_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U08_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U08_fingerprint_clean). Qed.
  Theorem U08_fingerprint_monotone : forall W, (forall p, In p U08_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U08_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U08_discharged_by *)
  (* class=nominal closure=open *)
  Definition U08_discharged_by_names : list string := ["gpg"].
  Lemma U08_discharged_by_clean : ~ In "echo" U08_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U08_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U08_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U08_discharged_by_clean). Qed.
  Theorem U08_discharged_by_monotone : forall W, (forall p, In p U08_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U08_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U09_fingerprint *)
  (* class=nominal closure=open *)
  Definition U09_fingerprint_names : list string := ["git"; "git"].
  Lemma U09_fingerprint_clean : ~ In "echo" U09_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U09_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U09_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U09_fingerprint_clean). Qed.
  Theorem U09_fingerprint_monotone : forall W, (forall p, In p U09_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U09_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U09_discharged_by *)
  (* class=nominal closure=open *)
  Definition U09_discharged_by_names : list string := ["git"; "git"; "git"].
  Lemma U09_discharged_by_clean : ~ In "echo" U09_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U09_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U09_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U09_discharged_by_clean). Qed.
  Theorem U09_discharged_by_monotone : forall W, (forall p, In p U09_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U09_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U10_fingerprint *)
  (* class=nominal closure=open *)
  Definition U10_fingerprint_names : list string := ["jq"].
  Lemma U10_fingerprint_clean : ~ In "echo" U10_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U10_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U10_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U10_fingerprint_clean). Qed.
  Theorem U10_fingerprint_monotone : forall W, (forall p, In p U10_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U10_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U10_discharged_by *)
  (* class=composed closure=host *)
  Definition U10_discharged_by_names : list string := ["jq"].
  Lemma U10_discharged_by_clean : ~ In "echo" U10_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U10_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U10_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U10_discharged_by_clean). Qed.
  Theorem U10_discharged_by_monotone : forall W, (forall p, In p U10_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U10_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.
  (* pattern 0: '^Read$' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem U10_discharged_by_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE U12_fingerprint *)
  (* class=nominal closure=open *)
  Definition U12_fingerprint_names : list string := ["git"; "patch"].
  Lemma U12_fingerprint_clean : ~ In "echo" U12_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U12_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U12_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U12_fingerprint_clean). Qed.
  Theorem U12_fingerprint_monotone : forall W, (forall p, In p U12_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U12_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U12_discharged_by *)
  (* class=composed closure=host *)
  Definition U12_discharged_by_names : list string := ["rg"; "grep"].
  Lemma U12_discharged_by_clean : ~ In "echo" U12_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U12_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U12_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U12_discharged_by_clean). Qed.
  Theorem U12_discharged_by_monotone : forall W, (forall p, In p U12_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U12_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.
  (* pattern 0: '^Grep$' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem U12_discharged_by_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE U13_fingerprint *)
  (* class=nominal closure=open *)
  Definition U13_fingerprint_names : list string := ["git"; "patch"].
  Lemma U13_fingerprint_clean : ~ In "echo" U13_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U13_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U13_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U13_fingerprint_clean). Qed.
  Theorem U13_fingerprint_monotone : forall W, (forall p, In p U13_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U13_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U13_discharged_by *)
  (* class=nominal closure=open *)
  Definition U13_discharged_by_names : list string := ["git"].
  Lemma U13_discharged_by_clean : ~ In "echo" U13_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U13_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U13_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U13_discharged_by_clean). Qed.
  Theorem U13_discharged_by_monotone : forall W, (forall p, In p U13_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U13_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U19_fingerprint *)
  (* class=nominal closure=open *)
  Definition U19_fingerprint_names : list string := ["sed"; "perl"].
  Lemma U19_fingerprint_clean : ~ In "echo" U19_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U19_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U19_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U19_fingerprint_clean). Qed.
  Theorem U19_fingerprint_monotone : forall W, (forall p, In p U19_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U19_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U19_discharged_by *)
  (* class=composed closure=host *)
  Definition U19_discharged_by_names : list string := ["cmp"; "sha256sum"; "shasum"; "rg"; "grep"; "diff"].
  Lemma U19_discharged_by_clean : ~ In "echo" U19_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U19_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U19_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U19_discharged_by_clean). Qed.
  Theorem U19_discharged_by_monotone : forall W, (forall p, In p U19_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U19_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.
  (* pattern 0: '^Grep$' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem U19_discharged_by_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE U20_fingerprint *)
  (* class=nominal closure=open *)
  Definition U20_fingerprint_names : list string := ["rm"; "truncate"; "git"].
  Lemma U20_fingerprint_clean : ~ In "echo" U20_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U20_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U20_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U20_fingerprint_clean). Qed.
  Theorem U20_fingerprint_monotone : forall W, (forall p, In p U20_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U20_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U20_discharged_by *)
  (* class=nominal closure=open *)
  Definition U20_discharged_by_names : list string := ["pytest"; "curl"; "go"; "cargo"; "npm"].
  Lemma U20_discharged_by_clean : ~ In "echo" U20_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U20_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U20_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U20_discharged_by_clean). Qed.
  Theorem U20_discharged_by_monotone : forall W, (forall p, In p U20_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U20_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U24_fingerprint *)
  (* class=nominal closure=open *)
  Definition U24_fingerprint_names : list string := ["npm"; "twine"; "cargo"].
  Lemma U24_fingerprint_clean : ~ In "echo" U24_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U24_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U24_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U24_fingerprint_clean). Qed.
  Theorem U24_fingerprint_monotone : forall W, (forall p, In p U24_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U24_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U24_discharged_by *)
  (* class=nominal closure=open *)
  Definition U24_discharged_by_names : list string := ["pytest"; "tox"; "nox"; "unittest"; "cargo"; "npm"; "pnpm"; "yarn"; "go"; "node"; "pytest"; "unittest"; "nox"; "tox"].
  Lemma U24_discharged_by_clean : ~ In "echo" U24_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U24_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U24_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U24_discharged_by_clean). Qed.
  Theorem U24_discharged_by_monotone : forall W, (forall p, In p U24_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U24_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

  (* SIDE U25_fingerprint *)
  (* class=nominal closure=open *)
  Definition U25_fingerprint_names : list string := ["go"; "cargo"; "npm"].
  Lemma U25_fingerprint_clean : ~ In "echo" U25_fingerprint_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U25_fingerprint_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U25_fingerprint_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U25_fingerprint_clean). Qed.
  Theorem U25_fingerprint_monotone : forall W, (forall p, In p U25_fingerprint_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U25_fingerprint_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.
  (* pattern 0: '(?i).*scan(?:ner)?\\w*\\.py' -- a regular vocabulary, checked in Python to exclude 'echo'; the instance is conditional on that. *)
  Theorem U25_fingerprint_pattern0_immune : forall V : string -> Prop,
    ~ V "echo" -> mention_immune Text mention (structural Text string scan V).
  Proof. intros V H. exact (structural_immune Text string scan mention "echo" scan_mention_single V H). Qed.

  (* SIDE U25_discharged_by *)
  (* class=nominal closure=open *)
  Definition U25_discharged_by_names : list string := ["pytest"; "unittest"; "go"; "cargo"; "npm"].
  Lemma U25_discharged_by_clean : ~ In "echo" U25_discharged_by_names.
  Proof. simpl; intuition discriminate. Qed.
  Theorem U25_discharged_by_immune :
    mention_immune Text mention (structural Text string scan (fun p => In p U25_discharged_by_names)).
  Proof. exact (structural_immune Text string scan mention "echo" scan_mention_single _ U25_discharged_by_clean). Qed.
  Theorem U25_discharged_by_monotone : forall W, (forall p, In p U25_discharged_by_names -> W p) ->
    forall c, nominal Text string scan (fun p => In p U25_discharged_by_names) c -> nominal Text string scan W c.
  Proof. intros W H. exact (nominal_monotone Text string scan _ W H). Qed.

End Instance.

Print Assumptions A01_fingerprint_clean.
Print Assumptions A01_fingerprint_immune.
Print Assumptions A01_fingerprint_monotone.
Print Assumptions A01_discharged_by_clean.
Print Assumptions A01_discharged_by_immune.
Print Assumptions A01_discharged_by_monotone.
Print Assumptions A02_fingerprint_clean.
Print Assumptions A02_fingerprint_immune.
Print Assumptions A02_fingerprint_monotone.
Print Assumptions A02_discharged_by_clean.
Print Assumptions A02_discharged_by_immune.
Print Assumptions A02_discharged_by_monotone.
Print Assumptions A03_fingerprint_clean.
Print Assumptions A03_fingerprint_immune.
Print Assumptions A03_fingerprint_monotone.
Print Assumptions A03_discharged_by_clean.
Print Assumptions A03_discharged_by_immune.
Print Assumptions A03_discharged_by_monotone.
Print Assumptions C08_check_can_fail_activated_by_pattern0_immune.
Print Assumptions C08_check_can_fail_discharged_by_pattern0_immune.
Print Assumptions C09_checker_excludes_self_fingerprint_name_agnostic.
Print Assumptions C09_checker_excludes_self_discharged_by_name_agnostic.
Print Assumptions T01_discharged_by_clean.
Print Assumptions T01_discharged_by_immune.
Print Assumptions T01_discharged_by_monotone.
Print Assumptions T02_activated_by_clean.
Print Assumptions T02_activated_by_immune.
Print Assumptions T02_activated_by_monotone.
Print Assumptions T02_discharged_by_clean.
Print Assumptions T02_discharged_by_immune.
Print Assumptions T02_discharged_by_monotone.
Print Assumptions U01_fingerprint_clean.
Print Assumptions U01_fingerprint_immune.
Print Assumptions U01_fingerprint_monotone.
Print Assumptions U01_discharged_by_clean.
Print Assumptions U01_discharged_by_immune.
Print Assumptions U01_discharged_by_monotone.
Print Assumptions U02_fingerprint_clean.
Print Assumptions U02_fingerprint_immune.
Print Assumptions U02_fingerprint_monotone.
Print Assumptions U02_discharged_by_clean.
Print Assumptions U02_discharged_by_immune.
Print Assumptions U02_discharged_by_monotone.
Print Assumptions U03_fingerprint_clean.
Print Assumptions U03_fingerprint_immune.
Print Assumptions U03_fingerprint_monotone.
Print Assumptions U03_discharged_by_clean.
Print Assumptions U03_discharged_by_immune.
Print Assumptions U03_discharged_by_monotone.
Print Assumptions U06_fingerprint_clean.
Print Assumptions U06_fingerprint_immune.
Print Assumptions U06_fingerprint_monotone.
Print Assumptions U06_discharged_by_clean.
Print Assumptions U06_discharged_by_immune.
Print Assumptions U06_discharged_by_monotone.
Print Assumptions U08_fingerprint_clean.
Print Assumptions U08_fingerprint_immune.
Print Assumptions U08_fingerprint_monotone.
Print Assumptions U08_discharged_by_clean.
Print Assumptions U08_discharged_by_immune.
Print Assumptions U08_discharged_by_monotone.
Print Assumptions U09_fingerprint_clean.
Print Assumptions U09_fingerprint_immune.
Print Assumptions U09_fingerprint_monotone.
Print Assumptions U09_discharged_by_clean.
Print Assumptions U09_discharged_by_immune.
Print Assumptions U09_discharged_by_monotone.
Print Assumptions U10_fingerprint_clean.
Print Assumptions U10_fingerprint_immune.
Print Assumptions U10_fingerprint_monotone.
Print Assumptions U10_discharged_by_clean.
Print Assumptions U10_discharged_by_immune.
Print Assumptions U10_discharged_by_monotone.
Print Assumptions U10_discharged_by_pattern0_immune.
Print Assumptions U12_fingerprint_clean.
Print Assumptions U12_fingerprint_immune.
Print Assumptions U12_fingerprint_monotone.
Print Assumptions U12_discharged_by_clean.
Print Assumptions U12_discharged_by_immune.
Print Assumptions U12_discharged_by_monotone.
Print Assumptions U12_discharged_by_pattern0_immune.
Print Assumptions U13_fingerprint_clean.
Print Assumptions U13_fingerprint_immune.
Print Assumptions U13_fingerprint_monotone.
Print Assumptions U13_discharged_by_clean.
Print Assumptions U13_discharged_by_immune.
Print Assumptions U13_discharged_by_monotone.
Print Assumptions U19_fingerprint_clean.
Print Assumptions U19_fingerprint_immune.
Print Assumptions U19_fingerprint_monotone.
Print Assumptions U19_discharged_by_clean.
Print Assumptions U19_discharged_by_immune.
Print Assumptions U19_discharged_by_monotone.
Print Assumptions U19_discharged_by_pattern0_immune.
Print Assumptions U20_fingerprint_clean.
Print Assumptions U20_fingerprint_immune.
Print Assumptions U20_fingerprint_monotone.
Print Assumptions U20_discharged_by_clean.
Print Assumptions U20_discharged_by_immune.
Print Assumptions U20_discharged_by_monotone.
Print Assumptions U24_fingerprint_clean.
Print Assumptions U24_fingerprint_immune.
Print Assumptions U24_fingerprint_monotone.
Print Assumptions U24_discharged_by_clean.
Print Assumptions U24_discharged_by_immune.
Print Assumptions U24_discharged_by_monotone.
Print Assumptions U25_fingerprint_clean.
Print Assumptions U25_fingerprint_immune.
Print Assumptions U25_fingerprint_monotone.
Print Assumptions U25_fingerprint_pattern0_immune.
Print Assumptions U25_discharged_by_clean.
Print Assumptions U25_discharged_by_immune.
Print Assumptions U25_discharged_by_monotone.
