(* GENERATED by tools/render_coverings.py from plugin/keel/clauses.json -- do not edit.
   One line per side of every shipped clause; one enumeration and one result per class,
   instantiating proofs/Coverings.v on the sides of that class. tools/check_coq.py
   compiles this, grades every result for axioms, and censuses the sides from the index.
   PARAMETERS: *)
Require Import String.
Require Import Coverings.

  (* SIDE A01_fingerprint *) (* class=always closure=always *)
  (* SIDE A01_discharged_by *) (* class=effect closure=world effects=observed_read *)
  (* SIDE A02_fingerprint *) (* class=always closure=always *)
  (* SIDE A02_discharged_by *) (* class=composed closure=host *)
  (*   BRANCH A02_discharged_by_branch0 *) (* class=effect closure=world effects=observed_read *)
  (*   BRANCH A02_discharged_by_branch1 *) (* class=tool-enum closure=host *)
  (*   BRANCH A02_discharged_by_branch2 *) (* class=effect closure=world effects=report_paths *)
  (* SIDE A03_fingerprint *) (* class=always closure=always *)
  (* SIDE A03_discharged_by *) (* class=effect closure=world effects=remote_read *)
  (* SIDE C03-verify-what-returns_fingerprint *) (* class=always closure=always *)
  (* SIDE C03-verify-what-returns_activated_by *) (* class=tool-enum closure=host *)
  (* SIDE C03-verify-what-returns_discharged_by *) (* class=tool-enum closure=host *)
  (* SIDE C08-check-can-fail_fingerprint *) (* class=always closure=always *)
  (* SIDE C08-check-can-fail_activated_by *) (* class=effect closure=world effects=report_pass *)
  (* SIDE C08-check-can-fail_discharged_by *) (* class=effect closure=world effects=report_fail *)
  (* SIDE C09-checker-excludes-self_fingerprint *) (* class=effect closure=world effects=report_self *)
  (* SIDE C09-checker-excludes-self_discharged_by *) (* class=effect closure=world effects=report_listing *)
  (* SIDE D01_fingerprint *) (* class=tool-enum closure=host *)
  (* SIDE D01_discharged_by *) (* class=tool-enum closure=host *)
  (* SIDE P01_fingerprint *) (* class=tool-enum closure=host *)
  (* SIDE P01_discharged_by *) (* class=tool-enum closure=host *)
  (* SIDE P02_fingerprint *) (* class=tool-enum closure=host *)
  (* SIDE P02_discharged_by *) (* class=tool-enum closure=host *)
  (* SIDE T01_fingerprint *) (* class=always closure=always *)
  (* SIDE T01_discharged_by *) (* class=effect closure=world effects=observed_read *)
  (* SIDE T02_fingerprint *) (* class=always closure=always *)
  (* SIDE T02_activated_by *) (* class=effect closure=world effects=remote_ref_moved *)
  (* SIDE T02_discharged_by *) (* class=effect closure=world effects=remote_landed *)
  (* SIDE U01_fingerprint *) (* class=effect closure=world effects=pids_spawned *)
  (* SIDE U01_discharged_by *) (* class=effect closure=world effects=report_pass *)
  (* SIDE U02_fingerprint *) (* class=effect closure=world effects=pids_spawned_again *)
  (* SIDE U02_discharged_by *) (* class=effect closure=world effects=report_after_change *)
  (* SIDE U03_fingerprint *) (* class=effect closure=world effects=pids_gone *)
  (* SIDE U03_discharged_by *) (* class=effect closure=world effects=observed_read,report_pids *)
  (* SIDE U06_fingerprint *) (* class=effect closure=world effects=net_out *)
  (* SIDE U06_discharged_by *) (* class=effect closure=world effects=net_read *)
  (* SIDE U08_fingerprint *) (* class=effect closure=world effects=commit_signed *)
  (* SIDE U08_discharged_by *) (* class=effect closure=world effects=report_signature *)
  (* SIDE U09_fingerprint *) (* class=effect closure=world effects=head_switched *)
  (* SIDE U09_discharged_by *) (* class=effect closure=world effects=observed_read,report_ref *)
  (* SIDE U10_fingerprint *) (* class=effect closure=world effects=report_null *)
  (* SIDE U10_discharged_by *) (* class=composed closure=host *)
  (*   BRANCH U10_discharged_by_branch0 *) (* class=effect closure=world effects=report_structured *)
  (*   BRANCH U10_discharged_by_branch1 *) (* class=tool-enum closure=host *)
  (* SIDE U12_fingerprint *) (* class=effect closure=world effects=files_changed *)
  (* SIDE U12_discharged_by *) (* class=composed closure=host *)
  (*   BRANCH U12_discharged_by_branch0 *) (* class=tool-enum closure=host *)
  (*   BRANCH U12_discharged_by_branch1 *) (* class=tool-enum closure=host *)
  (*   BRANCH U12_discharged_by_branch2 *) (* class=effect closure=world effects=report_paths *)
  (* SIDE U13_fingerprint *) (* class=effect closure=world effects=files_changed *)
  (* SIDE U13_discharged_by *) (* class=composed closure=host *)
  (*   BRANCH U13_discharged_by_branch0 *) (* class=tool-enum closure=host *)
  (*   BRANCH U13_discharged_by_branch1 *) (* class=effect closure=world effects=report_paths *)
  (* SIDE U19_fingerprint *) (* class=effect closure=world effects=files_changed *)
  (* SIDE U19_discharged_by *) (* class=composed closure=host *)
  (*   BRANCH U19_discharged_by_branch0 *) (* class=tool-enum closure=host *)
  (*   BRANCH U19_discharged_by_branch1 *) (* class=tool-enum closure=host *)
  (*   BRANCH U19_discharged_by_branch2 *) (* class=effect closure=world effects=report_paths *)
  (* SIDE U20_fingerprint *) (* class=effect closure=world effects=files_removed,head_reset *)
  (* SIDE U20_discharged_by *) (* class=effect closure=world effects=report_fail,report_pass *)
  (* SIDE U24_fingerprint *) (* class=effect closure=world effects=net_out *)
  (* SIDE U24_discharged_by *) (* class=effect closure=world effects=report_nowarn *)
  (* SIDE U25_fingerprint *) (* class=effect closure=world effects=report_clean *)
  (* SIDE U25_discharged_by *) (* class=effect closure=world effects=report_fail *)

Inductive EffectSide :=
  | A01_discharged_by
  | A02_discharged_by_branch0
  | A02_discharged_by_branch2
  | A03_discharged_by
  | C08_check_can_fail_activated_by
  | C08_check_can_fail_discharged_by
  | C09_checker_excludes_self_fingerprint
  | C09_checker_excludes_self_discharged_by
  | T01_discharged_by
  | T02_activated_by
  | T02_discharged_by
  | U01_fingerprint
  | U01_discharged_by
  | U02_fingerprint
  | U02_discharged_by
  | U03_fingerprint
  | U03_discharged_by
  | U06_fingerprint
  | U06_discharged_by
  | U08_fingerprint
  | U08_discharged_by
  | U09_fingerprint
  | U09_discharged_by
  | U10_fingerprint
  | U10_discharged_by_branch0
  | U12_fingerprint
  | U12_discharged_by_branch2
  | U13_fingerprint
  | U13_discharged_by_branch1
  | U19_fingerprint
  | U19_discharged_by_branch2
  | U20_fingerprint
  | U20_discharged_by
  | U24_fingerprint
  | U24_discharged_by
  | U25_fingerprint
  | U25_discharged_by.

Theorem effect_sides_read_the_world_not_the_command :
  forall (s : EffectSide) (D : Type) (E : D -> Prop) (d d' : D), E d -> ~ E d' ->
    name_agnostic string (effect string E d)
    /\ (forall segs, effect string E d segs /\ ~ effect string E d' segs).
Proof.
  intros s D E d d' Hd Hd'.
  split; [ exact (effect_is_name_agnostic string D E d)
         | exact (effect_separates_same_segments string D E d d' Hd Hd') ].
Qed.

Print Assumptions effect_sides_read_the_world_not_the_command.
